#!/bin/bash
_MINON_ID="null"
_INSTALL_UNPRO_SALT=0

# Fix for AWS PATH
PATH="/usr/local/bin:$PATH"

while getopts ":i:" opt
do
  case "${opt}" in

    i )  _MINION_ID=$OPTARG ;;

    \?)  echo "Option does not exist : $OPTARG"
         exit 1
         ;;
  esac
done

if ! hash salt-call 2>/dev/null; then
  wget -q -O install_salt.sh https://bootstrap.saltstack.com
  if [ "$_MINION_ID" != "null" ]; then
    sh install_salt.sh -X -i $_MINION_ID -g https://github.com/TronPaul/salt.git git v2014.7.2
  else
    sh install_salt.sh -X -g https://github.com/TronPaul/salt.git git v2014.7.2
  fi
  _INSTALL_UNPRO_SALT=$?
else
  if [ "$_MINION_ID" != "null" ]; then
    echo $_MINION_ID > /etc/salt/minion_id
  fi
fi

if [ $_INSTALL_UNPRO_SALT -eq 0 ]; then
  DIR=`mktemp -d`
  wget -q -O $DIR/unpro-salt.tar.gz https://github.com/TronPaul/unpro-salt/archive/master.tar.gz
  tar -xzf $DIR/unpro-salt.tar.gz -C $DIR
  _MINION_ID=$(salt-call --out txt grains.get id | cut -d ' ' -f 2)
  _GRAIN_PATH="$DIR/unpro-salt-master/salt/grains/$_MINION_ID"
  if [ -f $_GRAIN_PATH ]; then
    cp $_GRAIN_PATH /etc/salt/grains
  fi
  if ! grep -q '######## unPRO salt minion config ########' /etc/salt/minion; then
    cp $DIR/unpro-salt-master/salt/minion /etc/salt/minion
  fi
  rm -rf /srv/salt
  rm -rf /srv/pillar
  cp -r $DIR/unpro-salt-master/state /srv/salt
  cp -r $DIR/unpro-salt-master/pillar /srv/pillar
  salt-call state.highstate
  rm -rf $DIR
fi
