#!/bin/bash
if hash unzip 2>/dev/null; then
  echo 'Error: unzip util not installed'
  exit 1
fi

if hash salt-call 2>/dev/null; then
  wget -O install_salt.sh https://bootstrap.saltstack.com
  sh install_salt.sh
fi

DIR=`mktemp -d`
cd $DIR
wget -q https://github.com/TronPaul/unpro-salt/archive/master.zip
unzip -q master.zip
rm -rf /srv/salt
rm -rf /srv/pillar
cp -r unpro-salt-master/state /srv/salt
cp -r unpro-salt-master/pillar /srv/pillar
salt-call state.highstate
rm -rf $DIR
