#!/bin/bash
_MINON_ID="null"
_INSTALL_UNPRO_SALT=0

while getopts ":i:" opt
do
  case "${opt}" in

    i )  _MINION_ID=$OPTARG ;;

    \?)  echo "Option does not exist : $OPTARG"
         exit 1
         ;;
  esac
done

if ! hash salt-call 2>/dev/null; then
  wget -q -O install_salt.sh https://bootstrap.saltstack.com
  if [ "$_MINION_ID" != "null" ]; then
    sh install_salt.sh -X -i $_MINION_ID
  else
    sh install_salt.sh -X
  fi
  _EXIT_CODE=$?
  if [ $_EXIT_CODE -eq 0 ]; then
    sed -i "s/^#file_client: remote$/file_client: local/g" /etc/salt/minion
    _EXIT_CODE=$?
  fi
  _INSTALL_UNPRO_SALT=$_EXIT_CODE
fi

if [ $_INSTALL_UNPRO_SALT -eq 0 ]; then
  DIR=`mktemp -d`
  wget -q -O $DIR/unpro-salt.tar.gz https://github.com/TronPaul/unpro-salt/archive/master.tar.gz
  tar -xzf $DIR/unpro-salt.tar.gz -C $DIR
  _MINION_ID=$(salt-call --out txt grains.get id | cut -d ' ' -f 2)
  _GRAIN_PATH="$DIR/unpro-salt-master/salt/grains/$_MINION_ID"
  if [ -f $_GRAIN_PATH ]; then
    install $_GRAIN_PATH /etc/salt/grains
  fi
  rm -rf /srv/salt
  rm -rf /srv/pillar
  cp -r $DIR/unpro-salt-master/state /srv/salt
  cp -r $DIR/unpro-salt-master/pillar /srv/pillar
  salt-call state.highstate
  rm -rf $DIR
fi
