#! /bin/sh

setterm -blank 0 -powersave off -powerdown 0
xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

/usr/games/dolphin-emu -e "$1"
