#!/bin/bash

# Fix for AWS PATH
PATH="/usr/local/bin:$PATH"
if ! hash salt-call 2>/dev/null; then
  echo "No salt installed!!!"
  exit 1
fi

# Add github rsa key
salt-call ssh.set_known_host hostname=github.com fingerprint='16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48' enc='ssh-rsa'
# Get/Update unpro-salt
if [ -d /srv/unpro-salt ]; then
  salt-call git.pull /srv/unpro-salt
else
  salt-call git.clone /srv/unpro-salt https://github.com/TronPaul/unpro-salt.git opts='--depth 1 --recursive'
fi
if [ ! -L /srv/salt ]; then
  ln -s /srv/unpro-salt/state /srv/salt
fi
if [ ! -L /srv/formulas ]; then
  ln -s /srv/unpro-salt/formulas /srv/formulas
fi
if [ ! -L /srv/pillar ]; then
  ln -s /srv/unpro-salt/pillar /srv/pillar
fi
if [ -f /etc/keys/teamunpro_deploy_id_rsa ]; then
  if [ -d /srv/unpro-pillar-secrets ]; then
    salt-call git.pull /srv/unpro-pillar-secrets identity=/etc/keys/teamunpro_deploy_id_rsa
  else
    salt-call git.clone /srv/unpro-pillar-secrets git@github.com:TronPaul/unpro-pillar-secrets.git opts='--depth 1' identity=/etc/keys/teamunpro_deploy_id_rsa
  fi
fi
if [ -d /srv/unpro-pillar-secrets ] && [ ! -L /srv/pillar-secrets ]; then
  ln -s /srv/unpro-pillar-secrets /srv/pillar-secrets
fi
# Copy grain if found
_MINION_ID=$(salt-call --out txt grains.get id | cut -d ' ' -f 2)
_GRAIN_PATH="/srv/unpro-salt/salt/grains/$_MINION_ID"
if [ -f $_GRAIN_PATH ]; then
  cp $_GRAIN_PATH /etc/salt/grains
fi
# Copy custom minion config
if ! grep -q '######## unPRO salt minion config ########' /etc/salt/minion; then
  cp /srv/unpro-salt/salt/minion /etc/salt/minion
fi
salt-call state.highstate
