#!/bin/bash
if ! hash salt-call 2>/dev/null; then
  echo "No salt installed!!!"
  exit 1
fi

DIR=`mktemp -d`
wget -q -O $DIR/unpro-salt.tar.gz https://github.com/TronPaul/unpro-salt/archive/master.tar.gz
tar -xzf $DIR/unpro-salt.tar.gz -C $DIR
_MINION_ID=$(salt-call --out txt grains.get id | cut -d ' ' -f 2)
_GRAIN_PATH="$DIR/unpro-salt-master/salt/grains/$_MINION_ID"
if [ -f $_GRAIN_PATH ]; then
  install $_GRAIN_PATH /etc/salt/grains
fi
rm -rf /srv/salt
rm -rf /srv/pillar
cp -r $DIR/unpro-salt-master/state /srv/salt
cp -r $DIR/unpro-salt-master/pillar /srv/pillar
salt-call state.highstate
rm -rf $DIR
