#!/bin/bash
#
# Script for teamunpro ppp connections
case "$5" in
        192.168.42.1)
                /sbin/route add -net 192.168.42.0 netmask 255.255.255.0 gw 192.168.42.1
        ;;
        *)
esac
exit 0
